### PR TITLE
Added step back when Amazon complains about throttling, added paramet…

### PR DESCRIPTION
**Pull request by davidwestlund**
…er log_group_prefix

### CODE REVIEW

**Comment by dayglojesus** [comment]
This patch appears to address issues #7 and #8. I am currently running this in a testing environment and so far it seems stable.

**Comment by lukewaite** [comment]
Merged. Thanks @davidwestlund.

**Comment by rajwilkhu** [comment]
@lukewaite great this is merged. When is this PR going to be available through logstash plugin install?

**Comment by lukewaite** [comment]
@rajwilkhu Sorry - I should have mentioned that. 

I tagged [v0.10.0](https://github.com/lukewaite/logstash-input-cloudwatch-logs/releases/tag/v0.10.0) which included this MR on Saturday, and it's been pushed to rubygems. It should already be available with `logstash plugin install`.

**Pull request merged**
