### PR TITLE
Fix loading aws-sdk

### PR DESCRIPTION
**Pull request by lukewaite**

### CODE REVIEW

**Comment by tedder** [comment]
I installed the current version and got the aws-sdk error. When I try to install this branch:

```logstash-plugin install /opt/logstash-plugins/logstash-input-cloudwatch_logs-0.10.0.gem
Validating /opt/logstash-plugins/logstash-input-cloudwatch_logs-0.10.0.gem
Installing logstash-input-cloudwatch_logs
Error Bundler::InstallError, retrying 1/10
An error occurred while installing logstash-core-event-java (5.3.0), and Bundler cannot continue.
Make sure that `gem install logstash-core-event-java -v '5.3.0'` succeeds before bundling.```

**Comment by tedder** [comment]
^ was likely a PEBKAC; my docker host was having networking issues. Will report back soon.

**Comment by lukewaite** [comment]
Merging this as I was able to validate the failure in #16 on v0.10.0 and also validate that this fixes the issue.

**Comment by lukewaite** [comment]
@tedder Didn't mean to dismiss - if you can't resolve that issue you mentioned, please open a follow-up issue.

**Comment by tedder** [comment]
Luke- no worries. This fixes my problem- issue incoming though.

**Pull request merged**
