### PR TITLE
Get all log groups matching log group prefix

### LINKED ISSUE #2: dynamic log group discovery?
I think it would be great if the plugin would discover all log groups or take a wildcard for log groups (I am thinking something like `/aws/lambda/*`) so that all new lambdas that are deployed will automatically be consumed.

Do you see any issues with this functionality? I see the open issue about rate-limiting that I suspect would be even bigger of a concern with something like this.

### PR DESCRIPTION
**Pull request by lukewaite**
Contribution received via patchfile.

Fixes #2

### CODE REVIEW

**Comment by lukewaite** [comment]
My primary concern with this patch as currently implemented is that this changes the behaviour of the `log_group` setting. Assuming it is always a prefix, and searching against it may be undesirable for some users.

Feedback is welcome as to how to implement. We could possibly add a `log_group_prefix` setting, and make `log_group` and `log_group_prefix` not required, but depend on at least one of them being set.

**Comment by lukewaite** [comment]
Optionally required inputs are handled during `register` by the beats plugin, so I think that would probably be the best way to go about it here. 
https://github.com/logstash-plugins/logstash-input-beats/blob/master/lib/logstash/inputs/beats.rb#L108-L113

Perhaps not ideal, since I don't think it's caught during a `--configtest`, but perhaps the best we can accomplish without a specific api being made available for a plugin to do more advanced configuration testing. If something like this exists, I'm missing it.

**Comment by Chintanvpatel** [comment]
Hello @lukewaite ,

This will be very useful in case if we have multiple log groups with same pattern. So we don't required to run multiple logstash services with same configuration. 

It will be good instead of giving prefix option, you can make "log_group" as array so we can give some specific log group names. 

Thanks.

**Comment by lukewaite** [comment]
Thanks for the input @Chintanvpatel. 

I think that there would be a use case for both prefix and array based log-group selection.

**Comment by dayglojesus** [comment]
First, this plugin saved me a ton of work, so thanks for sharing!

Second, 👍 on the patch -- this would be extremely useful. I'm trying to source CloudWatch logs for API Gateway and the naming convention for these logs is really odd and there doesn't appear to be anything one can do to control it...

Example: `API-Gateway-Execution-Logs_3e1cj9xz8i/test`

Each stage of the API gets its own "log-group" which makes the logstash input configuration... challenging.

**Comment by lukewaite** [comment]
These changes were included in the MR from @davidwestlund https://github.com/lukewaite/logstash-input-cloudwatch-logs/pull/9 which has just been merged.

**Comment by JoaoRXFernandes** [comment]
+1 for this one! Thanks!

**Pull request closed without merging**
